## Introduction to tensors
### Creating tensors
Pytorch tensors are created using `torch.Tensors()` = https://pytorch.org/docs/stable/tensors/html

In [11]:
# scalar标量
import torch
scalar = torch.tensor(7)
scalar


tensor(7)

In [12]:
scalar.ndim
#check the dimension of the scalar

0

In [13]:
scalar.item()
#帮助把from type scalar to numbers

7

In [14]:
# vector向量
vector1 = torch.tensor([1, 2, 3, 4])
vector2 = torch.tensor([[5, 6],[7, 8]])
print(vector1.ndim,vector2.ndim,vector1.shape,vector2.shape)




1 2 torch.Size([4]) torch.Size([2, 2])


In [15]:
# matrix矩阵
MATRIX = torch.tensor([[1, 2], 
                       [3, 4], 
                       [5, 6]])
MATRIX

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [16]:
MATRIX[0][1]
#row 1 col 2

tensor(2)

In [17]:
# TENSOR 
TENSOR=torch.tensor([[[1,2,3],
                      [2,3,4],
                      [2,1,1]]])
TENSOR.shape

torch.Size([1, 3, 3])

encountering scalar and vector, we will typically use a lower case letter
while using a matrix and tensor we will use upper case letter

### Random tensors
`start with random numbers -> look at data -> update random numbers ....loop` 
Torch random tensors- https://pytorch.org/docs/stable/generated/torch.rand.html

In [32]:
# Create a random tensor of size (3,4)
random_tensor=torch.rand(3,4)
random_tensor

tensor([[0.7081, 0.1214, 0.7142, 0.3703],
        [0.5091, 0.0926, 0.2581, 0.5995],
        [0.7329, 0.7957, 0.5992, 0.9267]])

In [33]:
random_tensor.ndim

2

In [34]:
# Create a random tensor with similar shape to an image tensot
random_image_size_tensor=torch.rand(size=(224,224,3))#height, width, color channel
random_image_size_tensor.shape,random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### Zeros and ones

In [36]:
#Create a tensor of all zeros
zeros=torch.zeros(3,4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [37]:
zeros*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [38]:
# Create a tensor of all ones
ones=torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [40]:
ones.dtype,random_tensor.dtype

(torch.float32, torch.float32)

### Creating a range of tensors and tensors-like

In [48]:
# Use torch.range()
a=torch.arange(start=1,end=10,step=0.2)
#end not included

In [50]:
# Creating tensors like
ten_zeros=torch.zeros_like(input=a)
ten_zeros

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

### Tensor datatypes

**Note:** Tensor datatype is one of the 3 big errors we will run into woth Pytorch

1.Tensors not in right datatype

2.Tensors not in right shape

3.Tensors not on right device

In [56]:
# Float 32 tensors
floar_32_tensor= torch.tensor([3.0, 6.0, 9.0],
                              dtype=None, # what datatype is the tensor(float 32 or float 16)
                              device="cuda",
                              requires_grad=False)
floar_32_tensor

tensor([3., 6., 9.], device='cuda:0')